(define (ascending? s)
  (if (or (null? s) (null? (cdr s)))
      #t
      (and (>= (car (cdr s)) (car s))
           (ascending? (cdr s)))))

(define (my-filter pred s)
(cond ((null? s) '())
      ((pred (car s)) (cons (car s) (my-filter pred (cdr s))))
      (else (my-filter pred (cdr s))))
    
    )

(define (interleave lst1 lst2) 
(cond ((and (null? lst1) (null? lst2)) '())
      ((null? lst1) (cons (car lst2) (interleave (cdr lst2) nil)))
      ((null? lst2) (cons (car lst1) (interleave (cdr lst1) nil)))
      (else (cons (car lst1) (interleave lst2 (cdr lst1))))
    )    
    )
;  rest = lst1 if lst2 == None
; (define (interleave lst1 lst2) 
;   (cond 
;     ((null? lst1) lst2)
;     ((null? lst2) lst1)
;     (else (cons (car lst1) (interleave lst2 (cdr lst1))))
;   )
; )
;  fail
; (define (no-repeats s) 
; (define (m-filter lst val)
; (cond ((null? lst) #t)
;      ((not (= val (car lst))) (m-filter (cdr lst) val))
;      (else #f))
;     )
; (define (m-form n-lst o-lst)
; (cond ((null? o-lst) n-lst)
;       ((m-filter n-lst (car o-lst)) (m-form (cons n-lst (car o-lst)) (cdr o-lst)))
;       (else ((m-form n-lst (cdr o-lst))))
;     )
;     )
; (m-form (cons (car s) nil) (cdr s))
;     )
(define (no-repeats s)
  (if (null? s) s
    (cons (car s)
      (no-repeats (filter (lambda (x) (not (= (car s) x))) (cdr s)))
      ))
)